

hexaPrint: hexaPrint.o
	gcc -o hexaPrint hexaPrint.o

hexaPrint.o: hexaPrint.c
	gcc -c -g -Wall hexaPrint.c


Bubblesort: Bubblesort.o
	gcc -o Bubblesort Bubblesort.o

Bubblesort.o: Bubblesort.c
	gcc -c -g -Wall Bubblesort.c

clean:
	rm -rf Bubblesort hexaPrint  *.o